# Generated by Django 4.2.6 on 2024-02-08 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_images_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='preview_text',
            field=models.TextField(default=''),
        ),
    ]
