# Generated by Django 4.2.6 on 2024-02-08 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_savedposts_savedposts_unique_saved_post_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloquedAutors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, max_length=1)),
                ('author', models.ForeignKey(db_column='author', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_authors', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, related_name='blocked_by', to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
            options={
                'verbose_name': 'Blocked Author',
                'verbose_name_plural': 'Blocked Authors',
                'db_table': 'blocked_authors',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='bloquedautors',
            constraint=models.UniqueConstraint(fields=('author', 'username'), name='unique_blocked_author_user'),
        ),
    ]
