# Generated by Django 4.2.6 on 2024-02-08 14:58

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0008_bloquedautors_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloquedAutors',
            new_name='BloquedAuthor',
        ),
    ]
