# Generated by Django 4.2.6 on 2024-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_bloquedautors_bloquedauthor'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedposts',
            name='reazon',
            field=models.TextField(blank=True, null=True),
        ),
    ]
