# Generated by Django 4.2.6 on 2024-02-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_savedposts_reazon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedposts',
            name='reazon',
        ),
        migrations.AddField(
            model_name='bloquedauthor',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
