# Generated by Django 4.2.6 on 2024-02-28 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('posts', '0011_remove_savedposts_reazon_bloquedauthor_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentXPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, max_length=1)),
            ],
            options={
                'verbose_name': 'Comment X Post',
                'verbose_name_plural': 'Comments X Posts',
                'db_table': 'comment_x_post',
                'ordering': ['comment_id'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='likes',
            name='unique_like_post_user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='username',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='username',
        ),
        migrations.AddField(
            model_name='likes',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='likes',
            name='user',
            field=models.ForeignKey(db_column='user', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='likes',
            constraint=models.UniqueConstraint(fields=('content_type', 'user', 'object_id'), name='unique_like_content_type_object_user'),
        ),
        migrations.AddField(
            model_name='commentxpost',
            name='comment_id',
            field=models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_posts', to='posts.comments'),
        ),
        migrations.AddField(
            model_name='commentxpost',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AddField(
            model_name='commentxpost',
            name='post_id',
            field=models.ForeignKey(db_column='post_id', on_delete=django.db.models.deletion.CASCADE, related_name='comment_posts', to='posts.posts'),
        ),
    ]
