# Generated by Django 4.2.6 on 2024-02-25 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchanges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reactions',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, max_length=1)),
                ('reaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('reaction', models.IntegerField(choices=[(1, 'Like'), (2, 'Dislike')])),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('exchange_item', models.ForeignKey(db_column='exchange_item', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_item_reaction', to='exchanges.exchangesitems')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
                'db_table': 'reactions',
            },
        ),
    ]
