# Generated by Django 4.2.6 on 2024-02-28 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_commentxpost_remove_likes_unique_like_post_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchanges', '0003_imagesxexchangesitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentXExchangesItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, max_length=1)),
                ('comment_id', models.ForeignKey(db_column='comment_id', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_item_comment', to='posts.comments')),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('exchange_item_id', models.ForeignKey(db_column='exchange_item_id', on_delete=django.db.models.deletion.CASCADE, related_name='exchange_item_comment', to='exchanges.exchangesitems')),
            ],
            options={
                'verbose_name': 'Comment for exchange item',
                'verbose_name_plural': 'Comments for exchange items',
                'db_table': 'comments_x_exchange_items',
                'ordering': ['comment_id'],
            },
        ),
    ]
