# Generated by Django 4.2.6 on 2024-02-29 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0004_commentxexchangesitems'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reactions',
        ),
    ]
