# Generated by Django 4.2.6 on 2024-02-29 01:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exchanges', '0005_delete_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesitems',
            name='tags',
            field=models.ManyToManyField(db_column='tags', to='exchanges.tags'),
        ),
        migrations.CreateModel(
            name='ExhangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('state', models.BooleanField(default=True, max_length=1)),
                ('created_by', models.ForeignKey(db_column='created_by', on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL, to_field='username')),
                ('desired_item', models.ForeignKey(db_column='desired_item', on_delete=django.db.models.deletion.CASCADE, related_name='desired_item', to='exchanges.exchangesitems')),
                ('item_offered', models.ForeignKey(db_column='item_offered', on_delete=django.db.models.deletion.CASCADE, related_name='item_offered', to='exchanges.exchangesitems')),
            ],
            options={
                'verbose_name': 'Exchange proposal',
                'db_table': 'exchage_proposal',
            },
        ),
        migrations.AddConstraint(
            model_name='exhangeproposal',
            constraint=models.UniqueConstraint(fields=('item_offered', 'desired_item'), name='pk_exchage_proposal'),
        ),
    ]
