# Generated by Django 4.2.6 on 2024-02-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchanges', '0006_exchangesitems_tags_exhangeproposal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangesitems',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exchangesitems',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('phone', 'Phone'), ('email', 'Email')], default='phone', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exhangeproposal',
            name='proposal_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exchangesitems',
            name='item_state',
            field=models.IntegerField(choices=[(1, 'Nuevo'), (2, 'Usado, Como nuevo'), (3, 'Usado')], default=3, null=True),
        ),
    ]
