# Generated by Django 4.1.7 on 2023-10-18 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RecyclePointType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        default="A", help_text="A=Active, I=Inactive", max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RecyclesTypes",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        default="A", help_text="A=Active, I=Inactive", max_length=1
                    ),
                ),
                (
                    "recycle_type_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=500)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "db_table": "recycle_types",
            },
        ),
        migrations.CreateModel(
            name="Routes",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        default="A", help_text="A=Active, I=Inactive", max_length=1
                    ),
                ),
                ("route_id", models.AutoField(primary_key=True, serialize=False)),
                ("route_name", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=100)),
                ("longitude", models.CharField(max_length=100)),
                ("reference_point", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "db_table": "routes",
            },
        ),
        migrations.CreateModel(
            name="Trucks",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        default="A", help_text="A=Active, I=Inactive", max_length=1
                    ),
                ),
                ("truck_id", models.AutoField(primary_key=True, serialize=False)),
                ("truck_name", models.CharField(max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
            ],
            options={
                "db_table": "trucks",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        default="A", help_text="A=Active, I=Inactive", max_length=1
                    ),
                ),
                ("schedule_id", models.AutoField(primary_key=True, serialize=False)),
                ("schedule_date", models.DateField()),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=250)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycling.routes",
                    ),
                ),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recycling.trucks",
                    ),
                ),
            ],
            options={
                "db_table": "schedules",
            },
        ),
        migrations.CreateModel(
            name="RecyclingPoints",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "state",
                    models.CharField(
                        default="A", help_text="A=Active, I=Inactive", max_length=1
                    ),
                ),
                (
                    "recycle_point_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("location_name", models.CharField(max_length=100)),
                ("location_address", models.CharField(max_length=100)),
                ("latitude", models.CharField(max_length=100)),
                ("longitude", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=250)),
                (
                    "created_by",
                    models.ForeignKey(
                        db_column="created_by",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        to_field="username",
                    ),
                ),
                (
                    "recycle_types",
                    models.ManyToManyField(
                        through="recycling.RecyclePointType",
                        to="recycling.recyclestypes",
                    ),
                ),
            ],
            options={
                "db_table": "recycling_points",
            },
        ),
        migrations.AddField(
            model_name="recyclepointtype",
            name="recycle_point",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recycling.recyclingpoints",
            ),
        ),
        migrations.AddField(
            model_name="recyclepointtype",
            name="recycle_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="recycling.recyclestypes",
            ),
        ),
    ]
