# Generated by Django 4.2.6 on 2023-10-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0003_reviews_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recyclepointtype',
            name='state',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='recyclestypes',
            name='state',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='recyclingpoints',
            name='state',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='state',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='routes',
            name='state',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='state',
            field=models.BooleanField(default=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='trucks',
            name='state',
            field=models.BooleanField(default=True, max_length=1),
        ),
    ]
