# Generated by Django 4.2.6 on 2023-11-12 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("recycling", "0005_alter_recyclepointtype_table_cities_and_more"),
    ]

    operations = [
        # migrations.AddField(
        #     model_name="recyclingpoints",
        #     name="city",
        #     field=models.ForeignKey(
        #         blank=True,
        #         db_column="city_id",
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="recycling.cities",
        #     ),
        # ),
        migrations.AlterModelTable(
            name="recyclepointtype",
            table="recycle_point_type",
        ),
        migrations.AlterModelTable(
            name="routes",
            table="routes",
        ),
        migrations.AlterModelTable(
            name="schedule",
            table="schedule",
        ),
        migrations.AlterModelTable(
            name="trucks",
            table="trucks",
        ),
        migrations.AlterModelTable(
            name="reviews",
            table="reviews",
        ),
    ]
