# Generated by Django 4.2.6 on 2023-11-15 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0006_recyclingpoints_city_alter_recyclepointtype_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoints',
            name='city',
            field=models.ForeignKey(blank=True, db_column='city_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='recycling.cities'),
        ),
    ]
