# Generated by Django 4.2.6 on 2023-11-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0007_recyclingpoints_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoints',
            name='cover',
            field=models.TextField(blank=True, null=True),
        ),
    ]
