# Generated by Django 4.2.6 on 2023-11-21 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycling', '0008_recyclingpoints_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='recyclingpoints',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recyclingpoints',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
